### ISSUE TITLE
Add actions for for example the downloads-counter. 

### ISSUE THREAD

**Issue by doekenorg** [doekenorg/gf-entries-in-excel#23]
Implement Wordpress actions system to make code less coupled, and more extendable.
The counter is now hardcoded and fixed in the code. This can be extracted to some sort of plugin style. This way this 'plugin' can contain it's own code and variables. This cleans up the code a lot.

**Comment by doekenorg** [comment]
Add reset possibility on this class too :(

**Comment by doekenorg** [comment]
https://wordpress.org/support/topic/reset-export-count/

**Comment by floatytheastronaut** [comment]
FreeScout #72732. <br>https://support.gravitykit.com/conversation/72732?folder_id=4
