### ISSUE TITLE
DateField.php

### ISSUE THREAD

**Issue by mircobabini** [doekenorg/gf-entries-in-excel#29]
Sorry for opening a new issue. Was trying to understand why the Date transformer is missing.
I'd love to help, but my time is no-time, so if you mind to implement it, I can assure you I will donate (well, I will even if you say "do it yourself!" 😂).

By the way, the date format is specified in the field: https://snag.gy/Og6pPL.jpg
So correct me if I'm wrong but all the info to implement it should be there.

Thanks

**Comment by doekenorg** [comment]
Not every field NEEDS a specific transformer. If it has no specific transformer, the base transformer is used. If you see a reason why that should change, let me know :) But it works right? Or am I missing something?

**Comment by mircobabini** [comment]
It works, but the date is not printed following the format specified into the field settings.

**Comment by doekenorg** [comment]
@mircobabini Fixed in the develop branch. Wil add this to the next version. But you can use it already if you want. Just add `DateField.php` to `src/Field` and overwrite `Transformer.php` with the new one in develop.
