### ISSUE TITLE
Excel download not working on ipad/iphone

### ISSUE THREAD

**Issue by mircobabini** [doekenorg/gf-entries-in-excel#35]
Tried to change:

`header('Content-Type: application/vnd.ms-excel');` to
`header('Content-Type: application/octet-stream');`

according to [this solved question](https://stackoverflow.com/questions/11449989/php-exporting-to-excel-on-ipad) but nothing.

**Comment by doekenorg** [comment]
Thanks for letting me know. Will check it out.

**Comment by doekenorg** [comment]
Hi @mircobabini, 

the problem is with the Content-type of the file. I have a patch in the next release, but you can update `AbstractPHPExcelRenderer` to say: 

```php
                header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
```

Please let me know if this helps.
