### ISSUE TITLE
Auto column width toggle

### ISSUE THREAD

**Issue by doekenorg** [doekenorg/gf-entries-in-excel#47]
The column width is stretched to the full width needed by default. We should be able to turn this off for a specific column if we want. Maybe even set a predefined width.

**Comment by websherpa** [comment]
Just adding a note that as a first step:
Even a simple toggle switch between "Default / Auto-Width" in the plugin_settings_fields would give user choice for entire document and would be simpler to implement (as opposed to the trickier predefined width or column specific widths options).

**Comment by doekenorg** [comment]
So maybe... not maybe at all, I'm sure of it: we should set a maximum column width. I'll make a hook for this. Some code required like this: 

```php
    protected function autoSizeColumns(Worksheet $worksheet, $columns_count)
    {
        for ($i = 1; $i <= $columns_count; $i++) {
            $worksheet->getColumnDimensionByColumn($i)->setAutoSize(true);
        }

        // set max width
        $max_width = 30; // change to what you need.
        $worksheet->calculateColumnWidths();

        foreach ($worksheet->getColumnDimensions() as $dimension) {
            if ($dimension->getWidth() > $max_width) {
                $dimension->setAutoSize(false);
                $dimension->setWidth($max_width);
            }
        }

        return $this;
    }
```
