### ISSUE TITLE
Add currency formatting to numeric fields

### ISSUE THREAD

**Issue by doekenorg** [doekenorg/gf-entries-in-excel#58]
In response to [this ticket](https://wordpress.org/support/topic/column-format-as-currency/) we should add a currency formatting for [`NumericValue`](https://github.com/doekenorg/gf-entries-in-excel/blob/master/src/Values/NumericValue.php).

PhpSpreadSheet has support for this by adding a `NumberFormat::FORMAT_*` to 
```php
$cell->getStyle()->getNumberFormat()->setNumberFormat()
```
But the predefined options are minimal; only containing dollar and euro. It should be easy to format as "currency" and provide some options like:

- placing of currency symbol (start or end)
- formatting of the numeric value (comma's or periods)
- Overwriting the currency symbol (and automatically fill it from currency fields)

**Comment by Liblastic** [comment]
I added a PR here
https://github.com/doekenorg/gf-entries-in-excel/pull/65

**Comment by doekenorg** [comment]
@Liblastic I think you ment #57 instead of this issue :-)
