### ISSUE TITLE
Download all forms at once in one file

### ISSUE THREAD

**Issue by doekenorg** [doekenorg/gf-entries-in-excel#9]
Maybe this can be placed in different worksheets. Also because of security reasons I'd make this without the public url.

**Comment by brendanmullan** [comment]
Awesome thanks for adding this! And yes totally agree, the download all shouldn't be a public URL.

**Comment by doekenorg** [comment]
@brendanmullan I've added the feature to the development branch. Would you be able to checkout this repo, do a composer install, and checkout if this works for you? Thanks!

<img width="550" alt="bulk-download" src="https://user-images.githubusercontent.com/529515/36447425-b0830204-1684-11e8-8b67-ac0ecd4e5837.png">

**Comment by brendanmullan** [comment]
Great! I'm out of office until Thursday but will absolutely check it and report back then! :-)

**Comment by brendanmullan** [comment]
Wow great work! If you add any future improvements I think naming the worksheets using the name of the form would be a nice addition if it's possible. Just thought about it as the site I just tested it on has around 15 forms and some of the information captured looks similar so it's hard to identify which sheet belongs to which form.

**Comment by doekenorg** [comment]
@brendanmullan Yeah good point. Saw the same thing. Initially the worksheets hat the same name as the form, but with a title longer than 31 characters (because 32 would be just terrible) things started to break. Probably going to add a worksheet title hook. Thanks for the input.

**Comment by brendanmullan** [comment]
No problem! Thanks for adding it in!

**Comment by doekenorg** [comment]
@brendanmullan little heads up: added the worksheet titles in 1.2.1. Enjoy, and thanks for the beer ;-)
